// Script to force a complete rebuild of Tailwind CSS
const { execSync } = require('child_process');
const path = require('path');
const fs = require('fs');

console.log('🔄 Starting Tailwind CSS rebuild process...');

// Path to the output CSS file that Tailwind generates
const outputPath = path.join(__dirname, 'src/app/globals.css');
const inputPath = path.join(__dirname, 'src/app/input.css');
const tempOutputPath = path.join(__dirname, 'src/app/tailwind-output.css');

try {
  // Create a temporary input file with just the Tailwind directives
  fs.writeFileSync(inputPath, `@tailwind base;
@tailwind components;
@tailwind utilities;`, 'utf8');

  // Force rebuild by running the Tailwind CLI directly
  const tailwindCommand = `npx tailwindcss --input=${inputPath} --output=${tempOutputPath} --minify`;

  console.log('⚙️ Executing Tailwind build command...');
  const stdout = execSync(tailwindCommand).toString();
  console.log(`✅ Tailwind build completed`);

  // Read generated output file
  const data = fs.readFileSync(tempOutputPath, 'utf8');
  
  // Merge the core Tailwind directives with the generated CSS and add imports
  const tailwindDirectives = `/* globals.css - Generated by rebuild-tailwind.js */
@tailwind base;
@tailwind components;
@tailwind utilities;

/* Importações de estilos externos - usando path relativo correto */
@import '../../styles/premium-styles.css';
@import '../../styles/premium.css';
@import '../../styles/portfolio-enhanced.css';
@import '../../styles/emergency-fix.css';

/* Import Tailwind utilities backup for solving style issues */
@import './tailwind-utilities.css';
@import './additional-tailwind-utilities.css';
@import './tailwind-fallback.css';

`;
  
  // Write the merged content back to globals.css
  fs.writeFileSync(outputPath, tailwindDirectives + data, 'utf8');
  console.log(`✅ Successfully wrote combined CSS to globals.css`);
  
  // Clean up temporary files
  fs.unlinkSync(inputPath);
  fs.unlinkSync(tempOutputPath);
  console.log('✅ Cleaned up temporary files');

  console.log('🎉 Tailwind CSS rebuild process completed successfully');
  
} catch (error) {
  console.error(`❌ Error in Tailwind rebuild process: ${error.message}`);
  process.exit(1);
}
