name: Tailwind CSS Validation
on: [push, pull_request]
jobs:
  validate-tailwind:
    runs-on: ubuntu-latest
    env:
      # Placeholder environment variables for build-time only
      # Using .invalid TLD to ensure no accidental connections
      NEXT_PUBLIC_SUPABASE_URL: https://ci-build-placeholder.invalid
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ci-build-placeholder-anon-key
      SUPABASE_SERVICE_ROLE_KEY: ci-build-placeholder-service-key
      NEXT_PUBLIC_MERCADOPAGO_PUBLIC_KEY: ci-build-placeholder-mp-key
      MERCADOPAGO_ACCESS_TOKEN: ci-build-placeholder-mp-token
      # Skip Puppeteer download for faster builds (not used in build process)
      PUPPETEER_SKIP_DOWNLOAD: true
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9.0.0
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Validate Tailwind configuration
        run: node scripts/validate-tailwind.cjs
      - name: Type check
        run: pnpm typecheck
      - name: Build project
        run: pnpm build
      - name: Check for compiled CSS
        run: |
          if [ ! -d .next/static/css ]; then
            echo "No CSS files found in build output"
            exit 1
          fi
