name: Tailwind CSS Validation
on: [push, pull_request]
jobs:
  validate-tailwind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9.0.0
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Validate Tailwind configuration
        run: node scripts/validate-tailwind.js
      - name: Type check
        run: pnpm typecheck
      - name: Build project
        run: pnpm build
      - name: Check for compiled CSS
        run: |
          if [ ! -d .next/static/css ]; then
            echo "No CSS files found in build output"
            exit 1
          fi
